/*
 * TRANSLATION FILE (GERMAN)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 *
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Objekt anheben";
STR_R3F_LOG_action_heliporter_fait = "Objekt ""%1"" angehängt.";
STR_R3F_LOG_action_heliport_larguer = "Objekt absetzen";
STR_R3F_LOG_action_heliport_larguer_fait = "Objekt ""%1"" abgesetzt.";
STR_R3F_LOG_action_heliport_attente = "Anhaken... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Anhaken abgebrochen! Bleibe während des Einhaken über den Objekt.";

STR_R3F_LOG_action_deplacer_objet = "Nehme ""%1""";
STR_R3F_LOG_action_relacher_objet = "Löse ""%1""";
STR_R3F_LOG_action_aligner_pente = "Justiere an der Neigung";
STR_R3F_LOG_action_aligner_sol = "Justiere an den Boden";
STR_R3F_LOG_action_aligner_horizon = "Justiere horizontal";
STR_R3F_LOG_action_tourner = "Biegen Sie links/rechts ab (Tasten X / C)";
STR_R3F_LOG_action_rapprocher = "Näher/entfernter (Tasten F / R)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Sie können nicht in einem Fahrzeug einsteigen, während Sie dieses Objekt transportieren!";

STR_R3F_LOG_action_charger_deplace = "In Fahrzeug einladen";
STR_R3F_LOG_action_selectionner_objet_charge = "Lade ""%1"" in...";
STR_R3F_LOG_action_charger_selection = "... lade in ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Suche nun das Ziel für ""%1"" aus...";
STR_R3F_LOG_action_charger_en_cours = "Belanden in bearbeitung...";
STR_R3F_LOG_action_charger_fait = "Das Objekt ""%1"" ist in ""%2"" eingeladen.";
STR_R3F_LOG_action_charger_pas_assez_de_place = "In diesen Fahrzeug ist nicht genug Platz !";

STR_R3F_LOG_action_remorquer_direct = "Anhängen ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Hänge das Objekt an";
STR_R3F_LOG_action_detacher = "Hänge das Objekt ab";
STR_R3F_LOG_action_detacher_fait = "Objekt abgehängt.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Nur der Pilot kann das Objekt loslösen.";

STR_R3F_LOG_action_contenu_vehicule = "Fracht ansehen";
STR_R3F_LOG_action_decharger_en_cours = "Abladen in bearbeitung...";
STR_R3F_LOG_action_decharger_fait = "Das Objekt ""%1"" ist vom Fahrzeug abgeladen.";
STR_R3F_LOG_action_decharger_deja_fait = "Das Objekt ist schon abgeladen !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Einmal freigegeben, wird dieses Objekt nicht mehr manuell bewegbar sein.<br/>Wollen Sie die Aktion bestätigen?";

STR_R3F_LOG_action_ouvrir_usine = "Open the creation factory";
STR_R3F_LOG_action_creer_en_cours = "Creation in progress...";
STR_R3F_LOG_action_creer_fait = "The object ""%1"" has been created.";
STR_R3F_LOG_action_creer_pas_assez_credits = "The factory has not enough credits to create this object.";
STR_R3F_LOG_action_revendre_usine_direct = "Send back ""%1"" to the factory";
STR_R3F_LOG_action_revendre_usine_deplace = "Send back to the factory";
STR_R3F_LOG_action_revendre_usine_selection = "... send back to the factory";
STR_R3F_LOG_action_revendre_en_cours = "Sending back to the factory...";
STR_R3F_LOG_action_revendre_fait = "The object ""%1"" has been sent back to the factory.";
STR_R3F_LOG_action_revendre_decharger_avant = "You can't sent it back while its cargo content is not empty !";

STR_R3F_LOG_mutex_action_en_cours = "The current operation isn't finished !";
STR_R3F_LOG_joueur_dans_objet = "There is a player in the object ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "The object ""%1"" is already in transit !";
STR_R3F_LOG_objet_remorque_en_cours = "Impossible because the object ""%1"" is towing another object !";
STR_R3F_LOG_trop_loin = "Impossible because the object ""%1"" is too far !";

STR_R3F_LOG_dlg_CV_titre = "Fracht";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Laden : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "ABLADEN";
STR_R3F_LOG_dlg_CV_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_dlg_LO_titre = "Fabrik";
STR_R3F_LOG_dlg_LO_credits_restants = "Restguthaben : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "ERSTELLEN";
STR_R3F_LOG_dlg_LO_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Eigenschaften";
STR_R3F_LOG_nom_fonctionnalite_side = "Seite";
STR_R3F_LOG_nom_fonctionnalite_places = "Sitzplätze";
STR_R3F_LOG_nom_fonctionnalite_passif = "Es kann sein :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Bewegt von Spieler";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Angehoben";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Angehängt";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transportiert";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "Ladekosten %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Es kann :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Anheben";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Anhängen";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transport";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "max Ladung %1";

STR_R3F_LOG_deverrouillage_en_cours = "Entsperren... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Entsperren abgebrochen! Halten Sie das Ziel des Objektes während des Countdowns.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objekt entsperrt.";
STR_R3F_LOG_action_deverrouiller = "Entsperren ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Objekt gesperrt";